chat_model_name : qwen3.5-flash
api_key : sk-26d419f7324041ceb8adf1615518c8bf
embedding_model_name : text-embedding-v4
https_proxy : http://ip-api.com/json/
gaode_api_key : f3bcc7cea84e20480b3ce77f261f79a4

local_chat_model_name : qwen3:4b
local_embedding_model_name : nomic-embed-text-v2-moe


